# Generated by Django 2.0.7 on 2018-07-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Tutor'),
        ),
    ]
